package analizadorsintactico;

import javax.swing.JOptionPane;

public class InterfazCodigo extends javax.swing.JFrame {

    LogicaAnalizadorSemantico Operaciones = new LogicaAnalizadorSemantico();

    public InterfazCodigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Lugar_Codigo = new javax.swing.JTextArea();
        EjecutarAD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Mostar_Operaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lugar_Codigo.setColumns(20);
        Lugar_Codigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lugar_Codigo.setRows(5);
        jScrollPane1.setViewportView(Lugar_Codigo);

        EjecutarAD.setBackground(new java.awt.Color(255, 255, 255));
        EjecutarAD.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        EjecutarAD.setText("Ejecutar");
        EjecutarAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarADActionPerformed(evt);
            }
        });

        Mostar_Operaciones.setColumns(20);
        Mostar_Operaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Mostar_Operaciones.setRows(5);
        jScrollPane2.setViewportView(Mostar_Operaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(EjecutarAD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EjecutarAD)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EjecutarADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarADActionPerformed
        if (!Lugar_Codigo.getText().equals("") && !Mostar_Operaciones.getText().equals("")) {
            if (Operaciones.Separar_Codigo(Lugar_Codigo.getText()) == "") {
                Operaciones.Separa_CodigoOperaciones(Mostar_Operaciones.getText());
            } else {
                JOptionPane.showMessageDialog(null, Operaciones.Separar_Codigo(Lugar_Codigo.getText()));
            }
        } else {
            JOptionPane.showMessageDialog(null,"Por favor, escriba en los dos cuadros de texto");
        }
    }//GEN-LAST:event_EjecutarADActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EjecutarAD;
    private javax.swing.JTextArea Lugar_Codigo;
    private javax.swing.JTextArea Mostar_Operaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
